#ifndef DEVICEINFOPROVIDER_H
#define DEVICEINFOPROVIDER_H

#include <StandardDefines.h>
#include "IDeviceInfoProvider.h"
#include "DeviceDetail.h"

/* @Component */
class DeviceInfoProvider : public IDeviceInfoProvider {
    Public Virtual ~DeviceInfoProvider() = default;

    Public Virtual StdVector<DeviceDetail> GetAllSwitchDetails() override {
        StdVector<DeviceDetail> devices;
        
        // Add devices based on defined macros (SWITCH_1 to SWITCH_100)
        // For each switch, if both SWITCH_N_RELAY_PIN_INDEX and SWITCH_N_PHYSICAL_DEVICE_PIN_INDEX are defined, add the device
#if defined(SWITCH_1_RELAY_PIN_INDEX) && defined(SWITCH_1_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(1, SWITCH_1_RELAY_PIN_INDEX, SWITCH_1_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_2_RELAY_PIN_INDEX) && defined(SWITCH_2_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(2, SWITCH_2_RELAY_PIN_INDEX, SWITCH_2_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_3_RELAY_PIN_INDEX) && defined(SWITCH_3_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(3, SWITCH_3_RELAY_PIN_INDEX, SWITCH_3_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_4_RELAY_PIN_INDEX) && defined(SWITCH_4_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(4, SWITCH_4_RELAY_PIN_INDEX, SWITCH_4_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_5_RELAY_PIN_INDEX) && defined(SWITCH_5_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(5, SWITCH_5_RELAY_PIN_INDEX, SWITCH_5_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_6_RELAY_PIN_INDEX) && defined(SWITCH_6_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(6, SWITCH_6_RELAY_PIN_INDEX, SWITCH_6_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_7_RELAY_PIN_INDEX) && defined(SWITCH_7_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(7, SWITCH_7_RELAY_PIN_INDEX, SWITCH_7_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_8_RELAY_PIN_INDEX) && defined(SWITCH_8_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(8, SWITCH_8_RELAY_PIN_INDEX, SWITCH_8_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_9_RELAY_PIN_INDEX) && defined(SWITCH_9_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(9, SWITCH_9_RELAY_PIN_INDEX, SWITCH_9_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_10_RELAY_PIN_INDEX) && defined(SWITCH_10_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(10, SWITCH_10_RELAY_PIN_INDEX, SWITCH_10_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_11_RELAY_PIN_INDEX) && defined(SWITCH_11_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(11, SWITCH_11_RELAY_PIN_INDEX, SWITCH_11_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_12_RELAY_PIN_INDEX) && defined(SWITCH_12_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(12, SWITCH_12_RELAY_PIN_INDEX, SWITCH_12_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_13_RELAY_PIN_INDEX) && defined(SWITCH_13_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(13, SWITCH_13_RELAY_PIN_INDEX, SWITCH_13_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_14_RELAY_PIN_INDEX) && defined(SWITCH_14_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(14, SWITCH_14_RELAY_PIN_INDEX, SWITCH_14_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_15_RELAY_PIN_INDEX) && defined(SWITCH_15_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(15, SWITCH_15_RELAY_PIN_INDEX, SWITCH_15_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_16_RELAY_PIN_INDEX) && defined(SWITCH_16_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(16, SWITCH_16_RELAY_PIN_INDEX, SWITCH_16_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_17_RELAY_PIN_INDEX) && defined(SWITCH_17_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(17, SWITCH_17_RELAY_PIN_INDEX, SWITCH_17_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_18_RELAY_PIN_INDEX) && defined(SWITCH_18_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(18, SWITCH_18_RELAY_PIN_INDEX, SWITCH_18_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_19_RELAY_PIN_INDEX) && defined(SWITCH_19_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(19, SWITCH_19_RELAY_PIN_INDEX, SWITCH_19_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_20_RELAY_PIN_INDEX) && defined(SWITCH_20_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(20, SWITCH_20_RELAY_PIN_INDEX, SWITCH_20_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_21_RELAY_PIN_INDEX) && defined(SWITCH_21_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(21, SWITCH_21_RELAY_PIN_INDEX, SWITCH_21_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_22_RELAY_PIN_INDEX) && defined(SWITCH_22_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(22, SWITCH_22_RELAY_PIN_INDEX, SWITCH_22_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_23_RELAY_PIN_INDEX) && defined(SWITCH_23_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(23, SWITCH_23_RELAY_PIN_INDEX, SWITCH_23_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_24_RELAY_PIN_INDEX) && defined(SWITCH_24_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(24, SWITCH_24_RELAY_PIN_INDEX, SWITCH_24_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_25_RELAY_PIN_INDEX) && defined(SWITCH_25_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(25, SWITCH_25_RELAY_PIN_INDEX, SWITCH_25_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_26_RELAY_PIN_INDEX) && defined(SWITCH_26_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(26, SWITCH_26_RELAY_PIN_INDEX, SWITCH_26_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_27_RELAY_PIN_INDEX) && defined(SWITCH_27_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(27, SWITCH_27_RELAY_PIN_INDEX, SWITCH_27_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_28_RELAY_PIN_INDEX) && defined(SWITCH_28_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(28, SWITCH_28_RELAY_PIN_INDEX, SWITCH_28_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_29_RELAY_PIN_INDEX) && defined(SWITCH_29_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(29, SWITCH_29_RELAY_PIN_INDEX, SWITCH_29_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_30_RELAY_PIN_INDEX) && defined(SWITCH_30_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(30, SWITCH_30_RELAY_PIN_INDEX, SWITCH_30_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_31_RELAY_PIN_INDEX) && defined(SWITCH_31_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(31, SWITCH_31_RELAY_PIN_INDEX, SWITCH_31_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_32_RELAY_PIN_INDEX) && defined(SWITCH_32_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(32, SWITCH_32_RELAY_PIN_INDEX, SWITCH_32_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_33_RELAY_PIN_INDEX) && defined(SWITCH_33_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(33, SWITCH_33_RELAY_PIN_INDEX, SWITCH_33_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_34_RELAY_PIN_INDEX) && defined(SWITCH_34_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(34, SWITCH_34_RELAY_PIN_INDEX, SWITCH_34_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_35_RELAY_PIN_INDEX) && defined(SWITCH_35_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(35, SWITCH_35_RELAY_PIN_INDEX, SWITCH_35_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_36_RELAY_PIN_INDEX) && defined(SWITCH_36_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(36, SWITCH_36_RELAY_PIN_INDEX, SWITCH_36_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_37_RELAY_PIN_INDEX) && defined(SWITCH_37_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(37, SWITCH_37_RELAY_PIN_INDEX, SWITCH_37_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_38_RELAY_PIN_INDEX) && defined(SWITCH_38_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(38, SWITCH_38_RELAY_PIN_INDEX, SWITCH_38_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_39_RELAY_PIN_INDEX) && defined(SWITCH_39_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(39, SWITCH_39_RELAY_PIN_INDEX, SWITCH_39_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_40_RELAY_PIN_INDEX) && defined(SWITCH_40_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(40, SWITCH_40_RELAY_PIN_INDEX, SWITCH_40_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_41_RELAY_PIN_INDEX) && defined(SWITCH_41_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(41, SWITCH_41_RELAY_PIN_INDEX, SWITCH_41_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_42_RELAY_PIN_INDEX) && defined(SWITCH_42_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(42, SWITCH_42_RELAY_PIN_INDEX, SWITCH_42_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_43_RELAY_PIN_INDEX) && defined(SWITCH_43_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(43, SWITCH_43_RELAY_PIN_INDEX, SWITCH_43_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_44_RELAY_PIN_INDEX) && defined(SWITCH_44_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(44, SWITCH_44_RELAY_PIN_INDEX, SWITCH_44_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_45_RELAY_PIN_INDEX) && defined(SWITCH_45_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(45, SWITCH_45_RELAY_PIN_INDEX, SWITCH_45_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_46_RELAY_PIN_INDEX) && defined(SWITCH_46_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(46, SWITCH_46_RELAY_PIN_INDEX, SWITCH_46_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_47_RELAY_PIN_INDEX) && defined(SWITCH_47_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(47, SWITCH_47_RELAY_PIN_INDEX, SWITCH_47_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_48_RELAY_PIN_INDEX) && defined(SWITCH_48_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(48, SWITCH_48_RELAY_PIN_INDEX, SWITCH_48_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_49_RELAY_PIN_INDEX) && defined(SWITCH_49_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(49, SWITCH_49_RELAY_PIN_INDEX, SWITCH_49_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_50_RELAY_PIN_INDEX) && defined(SWITCH_50_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(50, SWITCH_50_RELAY_PIN_INDEX, SWITCH_50_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_51_RELAY_PIN_INDEX) && defined(SWITCH_51_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(51, SWITCH_51_RELAY_PIN_INDEX, SWITCH_51_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_52_RELAY_PIN_INDEX) && defined(SWITCH_52_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(52, SWITCH_52_RELAY_PIN_INDEX, SWITCH_52_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_53_RELAY_PIN_INDEX) && defined(SWITCH_53_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(53, SWITCH_53_RELAY_PIN_INDEX, SWITCH_53_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_54_RELAY_PIN_INDEX) && defined(SWITCH_54_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(54, SWITCH_54_RELAY_PIN_INDEX, SWITCH_54_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_55_RELAY_PIN_INDEX) && defined(SWITCH_55_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(55, SWITCH_55_RELAY_PIN_INDEX, SWITCH_55_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_56_RELAY_PIN_INDEX) && defined(SWITCH_56_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(56, SWITCH_56_RELAY_PIN_INDEX, SWITCH_56_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_57_RELAY_PIN_INDEX) && defined(SWITCH_57_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(57, SWITCH_57_RELAY_PIN_INDEX, SWITCH_57_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_58_RELAY_PIN_INDEX) && defined(SWITCH_58_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(58, SWITCH_58_RELAY_PIN_INDEX, SWITCH_58_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_59_RELAY_PIN_INDEX) && defined(SWITCH_59_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(59, SWITCH_59_RELAY_PIN_INDEX, SWITCH_59_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_60_RELAY_PIN_INDEX) && defined(SWITCH_60_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(60, SWITCH_60_RELAY_PIN_INDEX, SWITCH_60_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_61_RELAY_PIN_INDEX) && defined(SWITCH_61_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(61, SWITCH_61_RELAY_PIN_INDEX, SWITCH_61_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_62_RELAY_PIN_INDEX) && defined(SWITCH_62_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(62, SWITCH_62_RELAY_PIN_INDEX, SWITCH_62_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_63_RELAY_PIN_INDEX) && defined(SWITCH_63_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(63, SWITCH_63_RELAY_PIN_INDEX, SWITCH_63_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_64_RELAY_PIN_INDEX) && defined(SWITCH_64_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(64, SWITCH_64_RELAY_PIN_INDEX, SWITCH_64_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_65_RELAY_PIN_INDEX) && defined(SWITCH_65_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(65, SWITCH_65_RELAY_PIN_INDEX, SWITCH_65_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_66_RELAY_PIN_INDEX) && defined(SWITCH_66_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(66, SWITCH_66_RELAY_PIN_INDEX, SWITCH_66_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_67_RELAY_PIN_INDEX) && defined(SWITCH_67_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(67, SWITCH_67_RELAY_PIN_INDEX, SWITCH_67_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_68_RELAY_PIN_INDEX) && defined(SWITCH_68_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(68, SWITCH_68_RELAY_PIN_INDEX, SWITCH_68_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_69_RELAY_PIN_INDEX) && defined(SWITCH_69_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(69, SWITCH_69_RELAY_PIN_INDEX, SWITCH_69_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_70_RELAY_PIN_INDEX) && defined(SWITCH_70_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(70, SWITCH_70_RELAY_PIN_INDEX, SWITCH_70_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_71_RELAY_PIN_INDEX) && defined(SWITCH_71_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(71, SWITCH_71_RELAY_PIN_INDEX, SWITCH_71_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_72_RELAY_PIN_INDEX) && defined(SWITCH_72_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(72, SWITCH_72_RELAY_PIN_INDEX, SWITCH_72_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_73_RELAY_PIN_INDEX) && defined(SWITCH_73_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(73, SWITCH_73_RELAY_PIN_INDEX, SWITCH_73_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_74_RELAY_PIN_INDEX) && defined(SWITCH_74_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(74, SWITCH_74_RELAY_PIN_INDEX, SWITCH_74_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_75_RELAY_PIN_INDEX) && defined(SWITCH_75_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(75, SWITCH_75_RELAY_PIN_INDEX, SWITCH_75_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_76_RELAY_PIN_INDEX) && defined(SWITCH_76_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(76, SWITCH_76_RELAY_PIN_INDEX, SWITCH_76_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_77_RELAY_PIN_INDEX) && defined(SWITCH_77_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(77, SWITCH_77_RELAY_PIN_INDEX, SWITCH_77_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_78_RELAY_PIN_INDEX) && defined(SWITCH_78_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(78, SWITCH_78_RELAY_PIN_INDEX, SWITCH_78_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_79_RELAY_PIN_INDEX) && defined(SWITCH_79_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(79, SWITCH_79_RELAY_PIN_INDEX, SWITCH_79_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_80_RELAY_PIN_INDEX) && defined(SWITCH_80_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(80, SWITCH_80_RELAY_PIN_INDEX, SWITCH_80_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_81_RELAY_PIN_INDEX) && defined(SWITCH_81_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(81, SWITCH_81_RELAY_PIN_INDEX, SWITCH_81_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_82_RELAY_PIN_INDEX) && defined(SWITCH_82_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(82, SWITCH_82_RELAY_PIN_INDEX, SWITCH_82_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_83_RELAY_PIN_INDEX) && defined(SWITCH_83_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(83, SWITCH_83_RELAY_PIN_INDEX, SWITCH_83_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_84_RELAY_PIN_INDEX) && defined(SWITCH_84_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(84, SWITCH_84_RELAY_PIN_INDEX, SWITCH_84_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_85_RELAY_PIN_INDEX) && defined(SWITCH_85_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(85, SWITCH_85_RELAY_PIN_INDEX, SWITCH_85_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_86_RELAY_PIN_INDEX) && defined(SWITCH_86_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(86, SWITCH_86_RELAY_PIN_INDEX, SWITCH_86_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_87_RELAY_PIN_INDEX) && defined(SWITCH_87_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(87, SWITCH_87_RELAY_PIN_INDEX, SWITCH_87_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_88_RELAY_PIN_INDEX) && defined(SWITCH_88_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(88, SWITCH_88_RELAY_PIN_INDEX, SWITCH_88_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_89_RELAY_PIN_INDEX) && defined(SWITCH_89_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(89, SWITCH_89_RELAY_PIN_INDEX, SWITCH_89_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_90_RELAY_PIN_INDEX) && defined(SWITCH_90_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(90, SWITCH_90_RELAY_PIN_INDEX, SWITCH_90_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_91_RELAY_PIN_INDEX) && defined(SWITCH_91_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(91, SWITCH_91_RELAY_PIN_INDEX, SWITCH_91_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_92_RELAY_PIN_INDEX) && defined(SWITCH_92_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(92, SWITCH_92_RELAY_PIN_INDEX, SWITCH_92_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_93_RELAY_PIN_INDEX) && defined(SWITCH_93_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(93, SWITCH_93_RELAY_PIN_INDEX, SWITCH_93_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_94_RELAY_PIN_INDEX) && defined(SWITCH_94_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(94, SWITCH_94_RELAY_PIN_INDEX, SWITCH_94_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_95_RELAY_PIN_INDEX) && defined(SWITCH_95_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(95, SWITCH_95_RELAY_PIN_INDEX, SWITCH_95_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_96_RELAY_PIN_INDEX) && defined(SWITCH_96_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(96, SWITCH_96_RELAY_PIN_INDEX, SWITCH_96_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_97_RELAY_PIN_INDEX) && defined(SWITCH_97_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(97, SWITCH_97_RELAY_PIN_INDEX, SWITCH_97_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_98_RELAY_PIN_INDEX) && defined(SWITCH_98_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(98, SWITCH_98_RELAY_PIN_INDEX, SWITCH_98_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_99_RELAY_PIN_INDEX) && defined(SWITCH_99_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(99, SWITCH_99_RELAY_PIN_INDEX, SWITCH_99_PHYSICAL_DEVICE_PIN_INDEX));
#endif
#if defined(SWITCH_100_RELAY_PIN_INDEX) && defined(SWITCH_100_PHYSICAL_DEVICE_PIN_INDEX)
        devices.push_back(DeviceDetail(100, SWITCH_100_RELAY_PIN_INDEX, SWITCH_100_PHYSICAL_DEVICE_PIN_INDEX));
#endif
        
        return devices;
    }
};

#endif // DEVICEINFOPROVIDER_H
